---
- name: setup wsl
  hosts: all
  vars_files:
    - vars.yaml
  become: true

  pre_tasks:
    - name: upgrade apt repositories
      apt:
        update_cache: true

  roles:
    - zsh-user
    - powershell
    - vim
    - tmux
    - lastpass
    - docker-ce
    - python
    - misc
    - lastpass-user
    - docker-user
    - vim-user
    - tmux-user

  post_tasks:
    - name: cleanup apt packages
      apt:
        autoclean: true
        autoremove: true